### ISSUE TITLE
Lang

### ISSUE THREAD

**Issue by ioRekz** [alexdrel/i18n-react#1]
Hello, I don't understand where you should define messages for different languages.
Thanks !

**Comment by alexdrel** [comment]
Hi,

You can have it in a separate yam/json file or using highest level keys, e.g.:
```yaml
en:
  hello: Hello
fr:
 hello: Bonjour
de:
 hello: Hallo
``` 
Once the language is known you call T.setTexts passing the dictionary for the required language:

```js
var yaml=require('languages.yaml');
T.setTexts(yaml[UI_language]);
``` 

Determining UI language and download of the specific resource is out of scope for this library.
