### ISSUE TITLE
Translation in a placeholder returns an object

### ISSUE THREAD

**Issue by MathieuDebit** [alexdrel/i18n-react#26]
I have the following `.yml` file:

```yml
description:
      placeholder_1: "This is placeholder_1"
      placeholder_2: >
        This is placeholder_2
```

The first one renders a plain text as expected, but the second one returns an object:

![image](https://cloud.githubusercontent.com/assets/6206650/24396047/2ad51614-13a2-11e7-9e29-90e71647f300.png)

It's only a problem when use it inside a placeholder, witch returns `This is placeholder_2,[object Object]`.

Am I doing it wrong? Thanks!
